### ISSUE TITLE
How to use find function

### ISSUE THREAD

**Issue by piker00** [bonecode/BCHexEditor#2]
Dear Nils, can you pleas add in the demo sample of how to use find function. 
Thanks.

**Comment by NilsHoyer** [comment]
First of all: I didn't develop this package. Marcus did it and gave up 
this project 10 years before. I renamed it and published it here, since 
I love this hex editor and I believe it's and good add on to the BCEditor.

Marcus didn't support WideChar - I implemented it. But I never used a 
search.

Right now, I tried to implement a find - and I agree with you: It's too 
complicated. Additional WideChar is not supported. So we have to find a 
new implementation of the find feature.

(Btw: Regular Expressions are not implemented too until now.)

Since I implemented the find feature for the BCEditor new, I believe I 
can do this for the BCHexEditor too.

But until now, I'm not sure, what it should do. Can you assist me 
understanding this?

If I run the demo program and want to search for a string (maybe "Test") 
... what do I expect?

The BCHexEditor shows binary data. So I can match "Test" as 4 bytes. But 
should happens, if I search for unicode characters? They have two bytes...

Should the find feature only works with 2 byte characters? So how should 
a 4 byte string for "Test" fond on this?

There are a `UnicodeChars` property. Should I take it to decide if the 
find feature should search for AnsiChar or WideChar?

Or do we need to `Find` functions? One for binary (AnsiChar) and one for 
text (WideChar) search?

If I implement Regular Expressions ... should I convert the `Data` 
before the search from AnsiChar to WideChar?

If yes... how should I convert it? I saw, there are some conversions are 
implemented already. Maybe I should remove that implementation and 
should implement a CodePage translation from Windows?

But converting binary data with codepages ... does it make sense? 
Codepages should translate text data - not binary data.

So the BCHexEditor should know, if it shows text data, or binary data. 
Right? And for this, we need a new property, isn't it?

Maybe it would be good to have a `LoadFromStream` / `LoadFromFile` 
solution with `TEncoding`. What do you think?

Sorry about this many questions. If you are only looking for a working 
solution ... in the moment, I don't have it...

**Comment by NilsHoyer** [comment]
You are right: It wasn't usable until now.

I changed the `Find` function. Now you can search for a Unicode string or for binary data. As result, you get to position inside the data.

Please let me know, if you still don't understand the find function or if you get trouble with it.

**Comment by piker00** [comment]
I still can't use Find :(
from main demo
sample:
`BCHexEditor1.Find(  'run', 1, 1024, false);`

nothing happens

**Comment by piker00** [comment]
Sorry, that function returns pos, my bad :)
I was thinking that result must be highlighted automatically

**Comment by NilsHoyer** [comment]
I wondered about that too.

But I didn't developed the BCHexEditor. And in the moment, I prefer to optimize the BCEditor. So I will fix bugs in BCHexEditor, but I do not try to improve it otherwise in the moment. I'm sorry about this...

**Comment by piker00** [comment]
No problem, I remember this old component from the past.
Thanks for keeping this component alive
